Fix menko npc and add manual translation for Akari route
DazedMTL/RJ01043101 pull request #15
Opened 2023-07-17 16:55 UTC by shionels

- Fix menko hunting to hunter
- add manual translation for Akari affection 20 events

2023-07-17 16:58 UTC, shionels commented
Map 085, 086, 087 reverted one-liner because I used Translator++ for easier layout
I hope you don't mind beautify the json again, i already tested them and running fine
(maybe you can teach me your json beautify format)

2023-07-17 17:17 UTC, dazedanon commented
Yeah they will need to be formatted first before I can merge this. It's not too hard you just need VSCode. 

1. Open the JSON file in VSCode.
2. Right Click on the background.
3. Click Format.
OR
1. Open the JSON file in VSCode.
2. Hit Shift+Alt+F

![image](https://github.com/DazedMTL/RJ01043101/assets/96628874/d1c5d909-4b54-47d2-93e5-53422164948e)

2023-07-17 17:35 UTC, dazedanon requested changes
Left my reviews. Looks good overall, let me know when you make the changes.

2023-07-17 17:35 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "D_TEXT Defeat Kouta 15"
[Check this.](https://www.compart.com/en/unicode/U+202F)

2023-07-17 17:35 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "D_TEXT Let's defeat Mentaiko Hunter Boss! 15"
https://www.compart.com/en/unicode/U+202F

2023-07-17 17:35 UTC, dazedanon commented on www/data/CommonEvents.json
> +                    "D_TEXT Let's defeat Mentaiko Hunter Boss! 15"
https://www.compart.com/en/unicode/U+202F

2023-07-17 17:35 UTC, dazedanon commented on www/data/Enemies.json
> +        "name": "Master of Mentaiko Hunter",
Hunting makes more sense to me here. What do you think?

2023-07-17 17:35 UTC, dazedanon commented on www/data/Enemies.json
> +        "name": "Sanada of Mentaiko Hunter",
Here too

2023-07-17 17:35 UTC, dazedanon commented on www/data/Enemies.json
> +        "name": "God of Mentaiko Hunter Kanda",
Here too.

2023-07-17 17:35 UTC, dazedanon commented on www/data/Map085.json
Needs to be formatted.

2023-07-17 17:35 UTC, dazedanon commented on www/data/Map086.json
Needs to be formatted.

2023-07-17 17:35 UTC, dazedanon commented on www/data/Map087.json
Needs to be formatted.

2023-07-17 17:35 UTC, dazedanon commented on www/data/Map090.json
> -                                ">Mentaiko hunting that is said to be occurring in this town!\nRight-click on suspicious people and try to engage them in\nconversation. Let's set up a trap for the Me
Hunting makes more sense to me here. What do you think?

2023-07-17 17:35 UTC, dazedanon commented on www/data/Map091.json
> +                                "\\>Shiori: \\<I also thought that Mentaiko Hunter wasn't\nreally a big deal, but ..."
Hunting makes more sense to me here. What do you think?

2023-07-17 19:50 UTC, eromangaka commented
The unformatted json files appear to be really old? They match my 1.0.0 copy (but in english) but do not match anything recent. I dont know if these are full re-translations from scratch?

2023-07-17 20:05 UTC, dazedanon commented
> The unformatted json files appear to be really old? They match my 1.0.0 copy (but in english) but do not match anything recent. I dont know if these are full re-translations from scratch?

Are you sure? They seem to be fine when I compare them with Main.

![image](https://github.com/DazedMTL/RJ01043101/assets/96628874/d1a6a6a6-c629-49b7-bbc8-876f774086ee)

2023-07-17 20:46 UTC, eromangaka commented
Might just be the one i cherry picked, map086, looks like this against 1.0.0:
![image](https://github.com/DazedMTL/RJ01043101/assets/139575015/d5bf164b-f2b8-415e-8a32-7ebb2b394d51)


but like this against the file in main:
![image](https://github.com/DazedMTL/RJ01043101/assets/139575015/7061980f-02e9-4b57-bc14-2454af37aa85)

2023-07-18 00:43 UTC, shionels commented on www/data/CommonEvents.json
> +                    "D_TEXT Defeat Kouta 15"
it just reduction of existing line and I copied the space format since vscode highlighted it different than normal space
already tested and displayed okay in-game

2023-07-18 00:53 UTC, shionels commented on www/data/Enemies.json
> +        "name": "Master of Mentaiko Hunter",
i'm more leaning to consider that's the group name. usually japanese (informal) shorten kari-sha (one who hunts) to only kari at the end of the hunted object

2023-07-18 00:55 UTC, shionels commented on www/data/Map090.json
> -                                ">Mentaiko hunting that is said to be occurring in this town!\nRight-click on suspicious people and try to engage them in\nconversation. Let's set up a trap for the Me
this line might need better rewording later, i just swept replace menko hunting to hunter

2023-07-18 01:03 UTC, shionels commented
usually i fast-forward to the latest before i make my changes, but i might be messed up something on this time
i think i'll make another PR later and this one can be rejected/closed 
thank you very much for the review

2023-07-18 08:33 UTC, shionels commented
updated and has been fast-forwarded to the latest commit
mind if you take a look again?
let me know if i messed up something

2023-07-18 15:22 UTC, dazedanon commented
Looks good to me. Tested with main changes and didn't see any issues and the diffs look good. Thanks shionel!

2023-07-18 15:22 UTC, merged